; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define i32 @lower_urem_positive_odd(i32 %x) {
; CHECK-LABEL: lower_urem_positive_odd:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x9, #7589
; CHECK-NEXT:    movk x9, #4139, lsl #16
; CHECK-NEXT:    movk x9, #55878, lsl #32
; CHECK-NEXT:    mov w8, w0
; CHECK-NEXT:    movk x9, #689, lsl #48
; CHECK-NEXT:    mul x8, x8, x9
; CHECK-NEXT:    mov w9, #95
; CHECK-NEXT:    umulh x0, x8, x9
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 95
  ret i32 %1
}


define i32 @lower_urem_positive_even(i32 %x) {
; CHECK-LABEL: lower_urem_positive_even:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x9, #7172
; CHECK-NEXT:    movk x9, #61579, lsl #16
; CHECK-NEXT:    movk x9, #54159, lsl #32
; CHECK-NEXT:    mov w8, w0
; CHECK-NEXT:    movk x9, #61, lsl #48
; CHECK-NEXT:    mul x8, x8, x9
; CHECK-NEXT:    mov w9, #1060
; CHECK-NEXT:    umulh x0, x8, x9
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 1060
  ret i32 %1
}


; Don't lower if we can combine urem with udiv.
define i32 @combine_urem_udiv(i32 %x) {
; CHECK-LABEL: combine_urem_udiv:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #8969
; CHECK-NEXT:    movk w8, #22765, lsl #16
; CHECK-NEXT:    umull x8, w0, w8
; CHECK-NEXT:    lsr x8, x8, #32
; CHECK-NEXT:    sub w9, w0, w8
; CHECK-NEXT:    add w8, w8, w9, lsr #1
; CHECK-NEXT:    lsr w8, w8, #6
; CHECK-NEXT:    mov w9, #95
; CHECK-NEXT:    msub w9, w8, w9, w0
; CHECK-NEXT:    add w0, w9, w8
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 95
  %2 = udiv i32 %x, 95
  %3 = add i32 %1, %2
  ret i32 %3
}

; Don't lower for divisors that are a power of two.
define i32 @dont_lower_urem_power_of_two(i32 %x) {
; CHECK-LABEL: dont_lower_urem_power_of_two:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w0, w0, #0x3f
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 64
  ret i32 %1
}

; Don't lower if the divisor is one.
define i32 @dont_lower_urem_one(i32 %x) {
; CHECK-LABEL: dont_lower_urem_one:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 1
  ret i32 %1
}

; Don't lower if the divisor is 2^32.
define i32 @dont_lower_urem_i32_umax(i32 %x) {
; CHECK-LABEL: dont_lower_urem_i32_umax:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %1 = urem i32 %x, 4294967296
  ret i32 %1
}

; Don't lower i64 urem
define i64 @dont_lower_urem_i64(i64 %x) {
; CHECK-LABEL: dont_lower_urem_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x9, #58849
; CHECK-NEXT:    movk x9, #48148, lsl #16
; CHECK-NEXT:    movk x9, #33436, lsl #32
; CHECK-NEXT:    lsr x8, x0, #1
; CHECK-NEXT:    movk x9, #21399, lsl #48
; CHECK-NEXT:    umulh x8, x8, x9
; CHECK-NEXT:    lsr x8, x8, #4
; CHECK-NEXT:    mov w9, #98
; CHECK-NEXT:    msub x0, x8, x9, x0
; CHECK-NEXT:    ret
  %1 = urem i64 %x, 98
  ret i64 %1
}

@.str = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1

declare dso_local i32 @printf(i8* nocapture readonly, ...) local_unnamed_addr #1

define void @urem_loop(i32 %x) {
; CHECK-LABEL: urem_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x30, x23, [sp, #-48]! // 16-byte Folded Spill
; CHECK-NEXT:    stp x22, x21, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    .cfi_offset w19, -8
; CHECK-NEXT:    .cfi_offset w20, -16
; CHECK-NEXT:    .cfi_offset w21, -24
; CHECK-NEXT:    .cfi_offset w22, -32
; CHECK-NEXT:    .cfi_offset w23, -40
; CHECK-NEXT:    .cfi_offset w30, -48
; CHECK-NEXT:    mov x22, #7589
; CHECK-NEXT:    movk x22, #4139, lsl #16
; CHECK-NEXT:    movk x22, #55878, lsl #32
; CHECK-NEXT:    adrp x21, .L.str
; CHECK-NEXT:    mov w19, w0
; CHECK-NEXT:    mov w20, wzr
; CHECK-NEXT:    mov w0, #1
; CHECK-NEXT:    movk x22, #689, lsl #48
; CHECK-NEXT:    mov w23, #95
; CHECK-NEXT:    add x21, x21, :lo12:.L.str
; CHECK-NEXT:  .LBB7_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov w8, w0
; CHECK-NEXT:    mul x8, x8, x22
; CHECK-NEXT:    umulh x8, x8, x23
; CHECK-NEXT:    add w20, w8, w20
; CHECK-NEXT:    mov x0, x21
; CHECK-NEXT:    mov w1, w20
; CHECK-NEXT:    bl printf
; CHECK-NEXT:    cmp w0, w19
; CHECK-NEXT:    b.lo .LBB7_1
; CHECK-NEXT:  // %bb.2: // %afterloop
; CHECK-NEXT:    ldp x20, x19, [sp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x22, x21, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x30, x23, [sp], #48 // 16-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %0 = add i32 0, 0
  br label %loop
loop:
  %1 = phi i32 [ 1, %entry ], [ %5, %loop ]
  %2 = phi i32 [%0, %entry], [%4, %loop]
  %3 = urem i32 %1, 95
  %4 = add i32 %3, %2
  %5 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i32 %4)
  %6 = icmp ult i32 %5, %x
  br i1 %6, label %loop, label %afterloop

afterloop:
  ret void
}
