name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: TG908/fork-sync@beta
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: llvm
        base: master
        head: master
        
