name: Sync Fork

on:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: TG908/fork-sync@v1.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: llvm
        base: master
        head: master
        
